package encryption;
import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();

		//Read the key from the file generated by the client.
		ObjectInputStream inStream = new ObjectInputStream(new FileInputStream("keyFile.dat"));
		Key key = (Key) inStream.readObject(); 
		inStream.close();
	
		
		//Use the key to decrypt the incoming message from socket s.		
		Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
		cipher.init(Cipher.DECRYPT_MODE, key);
		CipherInputStream cipherStream= new CipherInputStream(s.getInputStream(),cipher);
	
		
		//Construct plaintext from the cipherStream
		int x = cipherStream.read();
		
		StringBuilder message = new StringBuilder();
		while( x >=0)
	     {	
			message.append((char) x);
	    	x=cipherStream.read();
	  
	     }
		
		//Print out the decrypt String to see if it matches the original message.
		System.out.println("The decrypted message is: "+ message.toString());
					
		cipherStream.close();
		server.close();
		
	}
}