package encryption;
import java.io.*;
import java.net.*;
import java.security.*;
import javax.crypto.*;

public class CipherServer
{
	public static void main(String[] args) throws Exception 
	{
		int port = 7999;
		ServerSocket server = new ServerSocket(port);
		Socket s = server.accept();

		//Read the key from the file generated by the client.
		ObjectInputStream fileIn = new ObjectInputStream(new FileInputStream("keyFile.dat"));
		ObjectInputStream inStream = new ObjectInputStream(s.getInputStream());
		Key key = (Key) fileIn.readObject(); 
		fileIn.close();
		
		//Use the key to decrypt the incoming message from socket s.		
		Cipher cipher = Cipher.getInstance("DES/ECB/PKCS5Padding");
        cipher.init(Cipher.DECRYPT_MODE, key);
        
        byte[] receivedByte = (byte[]) inStream.readObject();
		byte[] message = cipher.doFinal(receivedByte);
		
		//Print the message
		System.out.println("The deciphered message is: " + new String(message));
		
		inStream.close();
		server.close();
		
	}
}